# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GUImainWindow(object):
    def setupUi(self, GUImainWindow):
        GUImainWindow.setObjectName("GUImainWindow")
        GUImainWindow.resize(647, 522)
        self.centralwidget = QtWidgets.QWidget(GUImainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 80, 101, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 130, 141, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 230, 141, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 280, 101, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 20, 271, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CurrentData_files = QtWidgets.QListView(self.verticalLayoutWidget)
        self.CurrentData_files.setObjectName("CurrentData_files")
        self.verticalLayout.addWidget(self.CurrentData_files)
        self.Selected_files = QtWidgets.QListView(self.centralwidget)
        self.Selected_files.setGeometry(QtCore.QRect(260, 250, 271, 192))
        self.Selected_files.setObjectName("Selected_files")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 0, 20, 491))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 450, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 450, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 230, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 0, 141, 16))
        self.label_2.setObjectName("label_2")
        GUImainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GUImainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 21))
        self.menubar.setObjectName("menubar")
        self.menuThis_is_a_test = QtWidgets.QMenu(self.menubar)
        self.menuThis_is_a_test.setObjectName("menuThis_is_a_test")
        self.menuImport_Data = QtWidgets.QMenu(self.menuThis_is_a_test)
        self.menuImport_Data.setObjectName("menuImport_Data")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        GUImainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GUImainWindow)
        self.statusbar.setObjectName("statusbar")
        GUImainWindow.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtWidgets.QAction(GUImainWindow)
        self.actionTraining_Data.setObjectName("actionTraining_Data")
        self.actionTest_Data = QtWidgets.QAction(GUImainWindow)
        self.actionTest_Data.setObjectName("actionTest_Data")
        self.actionCurrent_Datasets = QtWidgets.QAction(GUImainWindow)
        self.actionCurrent_Datasets.setObjectName("actionCurrent_Datasets")
        self.actionSplice_Data = QtWidgets.QAction(GUImainWindow)
        self.actionSplice_Data.setObjectName("actionSplice_Data")
        self.actionDatasets_modification = QtWidgets.QAction(GUImainWindow)
        self.actionDatasets_modification.setObjectName("actionDatasets_modification")
        self.actionConfusion_Matrix = QtWidgets.QAction(GUImainWindow)
        self.actionConfusion_Matrix.setObjectName("actionConfusion_Matrix")
        self.actionConfusion_Matrix_2 = QtWidgets.QAction(GUImainWindow)
        self.actionConfusion_Matrix_2.setObjectName("actionConfusion_Matrix_2")
        self.actionTest_Data_Analysis_Report = QtWidgets.QAction(GUImainWindow)
        self.actionTest_Data_Analysis_Report.setObjectName("actionTest_Data_Analysis_Report")
        self.actionEdit_Feature_Vector_s = QtWidgets.QAction(GUImainWindow)
        self.actionEdit_Feature_Vector_s.setObjectName("actionEdit_Feature_Vector_s")
        self.actionManual_Mode_Switch = QtWidgets.QAction(GUImainWindow)
        self.actionManual_Mode_Switch.setObjectName("actionManual_Mode_Switch")
        self.menuImport_Data.addAction(self.actionTraining_Data)
        self.menuImport_Data.addAction(self.actionTest_Data)
        self.menuThis_is_a_test.addAction(self.menuImport_Data.menuAction())
        self.menuThis_is_a_test.addAction(self.actionCurrent_Datasets)
        self.menuThis_is_a_test.addAction(self.actionSplice_Data)
        self.menuEdit.addAction(self.actionDatasets_modification)
        self.menuEdit.addAction(self.actionEdit_Feature_Vector_s)
        self.menuEdit.addAction(self.actionManual_Mode_Switch)
        self.menuAnalysis.addAction(self.actionConfusion_Matrix)
        self.menuAnalysis.addAction(self.actionConfusion_Matrix_2)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionTest_Data_Analysis_Report)
        self.menubar.addAction(self.menuThis_is_a_test.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())

        self.retranslateUi(GUImainWindow)
        QtCore.QMetaObject.connectSlotsByName(GUImainWindow)

    def retranslateUi(self, GUImainWindow):
        _translate = QtCore.QCoreApplication.translate
        GUImainWindow.setWindowTitle(_translate("GUImainWindow", "MainWindow"))
        self.pushButton.setText(_translate("GUImainWindow", "Show All Datasets"))
        self.pushButton_2.setText(_translate("GUImainWindow", "Select Spacific Dataset(s)"))
        self.pushButton_3.setText(_translate("GUImainWindow", "Datasets Splicing"))
        self.pushButton_4.setText(_translate("GUImainWindow", "Feature Vectors Labellibg"))
        self.pushButton_5.setText(_translate("GUImainWindow", "Confusion Matrix"))
        self.pushButton_6.setText(_translate("GUImainWindow", "Add"))
        self.pushButton_7.setText(_translate("GUImainWindow", "Delete"))
        self.label.setText(_translate("GUImainWindow", "Selected Datasets"))
        self.label_2.setText(_translate("GUImainWindow", "All Datasets"))
        self.menuThis_is_a_test.setTitle(_translate("GUImainWindow", "File"))
        self.menuImport_Data.setTitle(_translate("GUImainWindow", "Import Data"))
        self.menuEdit.setTitle(_translate("GUImainWindow", "Edit"))
        self.menuAnalysis.setTitle(_translate("GUImainWindow", "Analysis"))
        self.actionTraining_Data.setText(_translate("GUImainWindow", "Training Data"))
        self.actionTest_Data.setText(_translate("GUImainWindow", "Test Data"))
        self.actionCurrent_Datasets.setText(_translate("GUImainWindow", "Current Selected Datasets"))
        self.actionSplice_Data.setText(_translate("GUImainWindow", "Splice Data and labelling"))
        self.actionDatasets_modification.setText(_translate("GUImainWindow", "Edit Selected Datasets"))
        self.actionConfusion_Matrix.setText(_translate("GUImainWindow", "Feature Vector Plotting"))
        self.actionConfusion_Matrix_2.setText(_translate("GUImainWindow", "Confusion Matrix"))
        self.actionTest_Data_Analysis_Report.setText(_translate("GUImainWindow", "Test Data Analysis Report"))
        self.actionEdit_Feature_Vector_s.setText(_translate("GUImainWindow", "Edit Feature Vector"))
        self.actionManual_Mode_Switch.setText(_translate("GUImainWindow", "Manual Mode Switch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUImainWindow = QtWidgets.QMainWindow()
    ui = Ui_GUImainWindow()
    ui.setupUi(GUImainWindow)
    GUImainWindow.show()
    sys.exit(app.exec_())

